name: composer ci-script

on:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: cache
        uses: actions/cache@v3
        with:
          key: docker-image#${{ hashFiles('./Dockerfile') }}
          path: ./docker-image.tar
      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          docker build . -t $GITHUB_REPOSITORY:latest
          docker image save -o ./docker-image.tar $GITHUB_REPOSITORY:latest
      - if: ${{ steps.cache.outputs.cache-hit == 'true' }}
        run: |
          docker image load -i ./docker-image.tar
      - uses: actions/cache@v3
        with:
          key: docker-run
          path: ./cache
      - name: Run COMPOSER_CACHE_DIR=$CACHE_DIR composer update --prefer-lowest
        run: >
          docker run
          --workdir /${{ GITHUB_REPOSITORY }}
          --volume ./:/${{ GITHUB_REPOSITORY }}
          --env CACHE_DIR=/${{ GITHUB_REPOSITORY }}/cache
          $GITHUB_REPOSITORY:latest
          -- true; COMPOSER_CACHE_DIR=$CACHE_DIR composer update --prefer-lowest
      - name: Run composer ci-script
        run: >
          docker run
          --workdir /${{ GITHUB_REPOSITORY }}
          --volume ./:/${{ GITHUB_REPOSITORY }}
          --env CACHE_DIR=/${{ GITHUB_REPOSITORY }}/cache
          $GITHUB_REPOSITORY:latest
          -- composer ci-script
